apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filebeat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:5.5.2
        resources:
          requests:
            cpu: 700m
            memory: 1024Mi
        ports:
        - containerPort: 5044
        volumeMounts:
           - mountPath: /usr/share/filebeat/data
             name: filebeat-data-registry
           - mountPath: /var/log/nginx
             name: nginx-logs-volume
             readOnly: true
           - mountPath: /usr/share/filebeat/filebeat.yml
             subPath: filebeat.yml
             name: filebeat-conf
             readOnly: true
      securityContext:
        seLinuxOptions:
          type: spc_t
      volumes:
      - name: filebeat-data-registry
        hostPath:
          path: /srv/filebeat/data
      - name: nginx-logs-volume
        hostPath:
          path: /srv/nginx/log
      - name: filebeat-conf
        configMap:
          name: filebeat-config
          items:
          - key: filebeat.yml
            path: filebeat.yml
