apiVersion: v1
kind: Service
metadata:
  labels:
    service: consul-slave
  name: consul-slave
spec:
  ports:
  - name: server-rpc
    port: 8300
    protocol: TCP
    targetPort: 8300
  - name: lan
    port: 8301
    protocol: TCP
    targetPort: 8301
  - name: wan
    port: 8302
    protocol: TCP
    targetPort: 8302
  - name: cli-rpc
    port: 8400
    protocol: TCP
    targetPort: 8400
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: dns1
    port: 8600
    protocol: TCP
    targetPort: 8600
  - name: dns2
    port: 8600
    protocol: TCP
    targetPort: 8600
  selector:
    service: consul-slave
status:
  loadBalancer: {}
