apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul-master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        service: consul-master
    spec:
      containers:
      - name: consul-master
        image: progrium/consul:latest
        args:
        - -server
        - -bootstrap-expect
        - "3"
        - -ui-dir
        - /ui
        ports:
        - name: server-rpc
          containerPort: 8300
          protocol: TCP
        - name: lan
          containerPort: 8301
          protocol: TCP
        - name: wan
          containerPort: 8302
          protocol: TCP
        - name: cli-rpc
          containerPort: 8400
          protocol: TCP
        - name: http
          containerPort: 8500
          protocol: TCP
        - name: dns1
          containerPort: 8600
          protocol: TCP
        - name: dns2
          containerPort: 53
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status:
  conditions:
  - type: Progressing
    status: "False"
    reason: progressDeadlineExceeded