apiVersion: v1
kind: Service
metadata:
  labels:
    service: elk
  name: elk
spec:
  ports:
  - name: port-1
    nodePort: 31892
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: port-2
    nodePort: 32610
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: port-3
    nodePort: 32680
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: port-4
    nodePort: 30259
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    service: elk
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}