apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elk
spec:
  template:
    metadata:
      labels:
        service: elk
    spec:
      containers:
        - image: elasticsearch:latest
          name: elasticsearch
          ports:
            - name: api
              containerPort: 9200
              protocol: TCP
            - name: cluster
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: es-storage
              mountPath: /usr/share/elasticsearch/data
        - image: logstash:latest
          args:
            - logstash
            - -f
            - /etc/logstash/conf.d/logstash.conf
          name: logstash
          env:
            - name: ELASTICSEARCH_URL
              value: http://127.0.0.1:9200
          ports:
            - name: json
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: logstash-config
              mountPath: /etc/logstash/conf.d
        - image: kibana
          name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: http://127.0.0.1:9200
          ports:
            - name: dashboard
              containerPort: 5601
              protocol: TCP
          volumeMounts:
            - name: kibana-config
              mountPath: /opt/kibana/config
            - name: logstash-config
              mountPath: /tmp/config
              # subPath: kibana
      volumes:
        - name: es-storage
          emptyDir: {}
        - name: kibana-config
          configMap:
            name: elk-config
            items:
            - key: kibana-config
              path: kibana.yml
        - name: logstash-config
          configMap:
            name: elk-config
            items:
            - key: logstash-config
              path: logstash.conf
        #   gitRepo:
        #     repository: https://github.com/rchicoli/kubernetes-microservices.git