apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
spec:
  template:
    metadata:
      labels:
        service: logstash
      namespace: default
    spec:
      containers:
        - image: logstash:5.4.0-alpine
        # - image: docker.elastic.co/logstash/logstash:5.5.2
          args:
            - logstash
            - -f
            - /etc/logstash/conf.d/logstash.conf
          name: logstash
          ports:
            - name: json
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: logstash-config
              mountPath: /etc/logstash/conf.d
            - name: logstash-patterns
              mountPath: /etc/logstash/patterns
          resources:
            limits:
              cpu: 300m
          lifecycle:
            postStart:
              exec:
                command: ["/bin/chmod", "644", "/etc/logstash/conf.d/logstash.conf"]
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
            items:
            - key: logstash.conf
              path: logstash.conf
        - name: logstash-patterns
          configMap:
            name: logstash-config
            items:
            - key: logstash.patterns
              path: nginx.grok