apiVersion: v1
kind: Service
metadata:
  labels:
    service: logstash
  name: logstash
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: json
  selector:
    service: logstash
status:
  loadBalancer: {}
