apiVersion: v1
kind: Service
metadata:
  labels:
    service: logstash
  name: logstash
spec:
  ports:
  - nodePort: 32074
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    service: logstash
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
